;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        markdown-cycle
        markdown-exdent-or-delete
        prelude-move-beginning-of-line
        sp-backward-delete-char
        sp-backward-kill-word
        sp-kill-hybrid-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        coffee-dedent-line-backspace
        haml-electric-backspace
        ido-list-directory
        kill-region
        mark-whole-buffer
        ns-copy-including-secondary
        projectile-ag
        rspec-rerun
        rspec-verify
        smex
        sp--self-insert-command
        yas-expand
        ))
